export const dev = window.location.origin.includes('localhost')
export const baseURL = dev ? 'http://localhost:3000' : ''
export const servePath = dev ? '' : '/bookclub/'
export const useSockets = false
export const domain = 'dev-eux5v4apdr8nm4hz.us.auth0.com'
export const audience = 'classroom2'
export const clientId = 'Rur2HYRUEOc9CFa5kFMGh67L2LmsuzQH'
export const gbak = 'AIzaSyBcf7Ry8H9mWxSzyfghzaS7sU0WN9Qxtj4'
export const ntak = 'NhL89IMsqCIzG7YABO2ybDtxKek7Mh1L'